version: "3.9"

networks:
    laravel:
        driver: bridge

volumes:
    mysql:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        depends_on:
            - php
            - pnpm
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    php:
        build:
            context: .docker/php
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: php
        restart: unless-stopped
        depends_on:
            - pnpm
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    pnpm:
        build:
            context: .
            dockerfile: pnpm.Dockerfile
        container_name: pnpm
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        ports:
            - 5173:5173
