version: "3.9"

networks:
    laravel:
        driver: bridge

volumes:
    mysql:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        depends_on:
            - php
            - yarn
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    php:
        build:
            context: .docker/php
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: php
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        depends_on:
            - yarn

    yarn:
        image: node:20-slim
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        ports:
            - 5173:5173
        working_dir: /var/www/html
        entrypoint: ["yarn", "run", "dev"]
